# Generated by Django 3.0.8 on 2020-07-09 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agegroup', models.CharField(blank=True, choices=[('1', 'א'), ('2', 'ב'), ('3', 'ג'), ('4', 'ד'), ('5', 'ה'), ('6', 'ו'), ('7', 'ז'), ('8', 'ח'), ('9', 'ט')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_in_year', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_title', models.CharField(help_text='Set the month title', max_length=20)),
                ('content', models.TextField(default='', help_text='Insert general month information', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('calendar', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='information', to='project.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Set starting time')),
                ('end_time', models.DateTimeField(help_text='Set ending time')),
                ('title', models.CharField(default='Peilut', help_text='Set the activity title', max_length=20)),
                ('content', models.TextField(blank=True, default='', max_length=50)),
                ('age_group', models.ManyToManyField(default='3', to='project.AgeGroup')),
                ('calendar', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='project.Calendar')),
            ],
        ),
    ]
