# Generated by Django 3.0.8 on 2020-07-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='age_group',
            field=models.CharField(default='ד', help_text='א/ב/ג/ד', max_length=5),
        ),
    ]
