# Generated by Django 3.0.8 on 2020-07-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Owner',
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='client',
            new_name='owner',
        ),
    ]
