# Generated by Django 3.0.8 on 2020-07-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_activity_age_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='calender',
            new_name='calendar',
        ),
        migrations.RenameField(
            model_name='activitymonth',
            old_name='calender',
            new_name='calendar',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='calender',
            new_name='calendar',
        ),
    ]
