# Generated by Django 3.0.8 on 2020-07-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_agegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='age_group',
            field=models.ManyToManyField(to='project.AgeGroup'),
        ),
    ]
